let a=0;
let b=1;
// a += b;
// console.log(a);
// a -= b;
// console.log(a);
// a *= b;
// console.log(a);
// a /= b;
// console.log(a);
// a %= b;
// console.log(a);
// a &= b;
// console.log(a);
// a |= b;
// console.log(a);
// a ^= b;
// console.log(a);
// a <<= b;
// console.log(a);
// a >>= b;
// console.log(a);
// a <<= b;
// console.log(a);
